//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptiveConsole.Config
{
    
    
    /// <summary>
    /// The AdaptiveConsoleConfiguration Configuration Section.
    /// </summary>
    public partial class AdaptiveConsoleConfiguration : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the AdaptiveConsoleConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AdaptiveConsoleConfigurationSectionName = "adaptiveConsole";
        
        /// <summary>
        /// The XML path of the AdaptiveConsoleConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AdaptiveConsoleConfigurationSectionPath = "adaptiveConsole";
        
        /// <summary>
        /// Gets the AdaptiveConsoleConfiguration instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public static global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration Instance
        {
            get
            {
                return ((global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration)(global::System.Configuration.ConfigurationManager.GetSection(global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration.AdaptiveConsoleConfigurationSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Provider Property
        /// <summary>
        /// The XML name of the <see cref="Provider"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ProviderPropertyName = "provider";
        
        /// <summary>
        /// Gets or sets gets or sets the name of the type which represents the console application instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("Gets or sets the name of the type which represents the console application instan" +
            "ce.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration.ProviderPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Provider
        {
            get
            {
                return ((string)(base[global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration.ProviderPropertyName]));
            }
            set
            {
                base[global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration.ProviderPropertyName] = value;
            }
        }
        #endregion
        
        #region Repositories Property
        /// <summary>
        /// The XML name of the <see cref="Repositories"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string RepositoriesPropertyName = "repositories";
        
        /// <summary>
        /// Gets or sets the Repositories.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Repositories.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration.RepositoriesPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::AdaptiveConsole.Config.ContractRepositoryElementCollection Repositories
        {
            get
            {
                return ((global::AdaptiveConsole.Config.ContractRepositoryElementCollection)(base[global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration.RepositoriesPropertyName]));
            }
            set
            {
                base[global::AdaptiveConsole.Config.AdaptiveConsoleConfiguration.RepositoriesPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace AdaptiveConsole.Config
{
    
    
    /// <summary>
    /// A collection of ContractRepositoryElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::AdaptiveConsole.Config.ContractRepositoryElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::AdaptiveConsole.Config.ContractRepositoryElementCollection.ContractRepositoryElementPropertyName)]
    public partial class ContractRepositoryElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ContractRepositoryElementPropertyName = "repository";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override string ElementName
        {
            get
            {
                return global::AdaptiveConsole.Config.ContractRepositoryElementCollection.ContractRepositoryElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::AdaptiveConsole.Config.ContractRepositoryElementCollection.ContractRepositoryElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::AdaptiveConsole.Config.ContractRepositoryElement)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::AdaptiveConsole.Config.ContractRepositoryElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::AdaptiveConsole.Config.ContractRepositoryElement this[int index]
        {
            get
            {
                return ((global::AdaptiveConsole.Config.ContractRepositoryElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::AdaptiveConsole.Config.ContractRepositoryElement this[object name]
        {
            get
            {
                return ((global::AdaptiveConsole.Config.ContractRepositoryElement)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="repository">The <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Add(global::AdaptiveConsole.Config.ContractRepositoryElement repository)
        {
            base.BaseAdd(repository);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="repository">The <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Remove(global::AdaptiveConsole.Config.ContractRepositoryElement repository)
        {
            base.BaseRemove(this.GetElementKey(repository));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::AdaptiveConsole.Config.ContractRepositoryElement GetItemAt(int index)
        {
            return ((global::AdaptiveConsole.Config.ContractRepositoryElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::AdaptiveConsole.Config.ContractRepositoryElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::AdaptiveConsole.Config.ContractRepositoryElement GetItemByKey(string name)
        {
            return ((global::AdaptiveConsole.Config.ContractRepositoryElement)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace AdaptiveConsole.Config
{
    
    
    /// <summary>
    /// The ContractRepositoryElement Configuration Element.
    /// </summary>
    public partial class ContractRepositoryElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::AdaptiveConsole.Config.ContractRepositoryElement.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::AdaptiveConsole.Config.ContractRepositoryElement.NamePropertyName]));
            }
            set
            {
                base[global::AdaptiveConsole.Config.ContractRepositoryElement.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region Assembly Property
        /// <summary>
        /// The XML name of the <see cref="Assembly"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AssemblyPropertyName = "assembly";
        
        /// <summary>
        /// Gets or sets the Assembly.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Assembly.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::AdaptiveConsole.Config.ContractRepositoryElement.AssemblyPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Assembly
        {
            get
            {
                return ((string)(base[global::AdaptiveConsole.Config.ContractRepositoryElement.AssemblyPropertyName]));
            }
            set
            {
                base[global::AdaptiveConsole.Config.ContractRepositoryElement.AssemblyPropertyName] = value;
            }
        }
        #endregion
    }
}
